### ISSUE TITLE
tablepress_rest_api:missing_capability:tablepress_edit_table

### ISSUE THREAD

**Issue by oldmanwerther** [TablePress/TablePress#173]
Any suggestions on why the endpoint is returning:

`{
"code": "tablepress_rest_api:missing_capability:tablepress_edit_table",
"message": "Sorry, you are not allowed to view this table.",
"data": {
"status": 401
}
}`

**Comment by TobiasBg** [comment]
Hi @oldmanwerther,

what exact endpoint are you calling, i.e. what's the full REST request that you are trying to perform?

Regards,
Tobias

**Comment by oldmanwerther** [comment]
https://douglas-dynamics-multi.local/wp-json/tablepress/v1/tables

Trying to get this setup locally first so I can read some table data from the Rest API.

**Comment by TobiasBg** [comment]
Hi @oldmanwerther,

thanks for the clarification! Essentially, the issue here is authentication. These requests must be made by a user that has the right to see the list of tables or to edit that specific table. This is the default setting for security reasons (tables can contain personal/private data after all, which is why they are not publicly exposed by the REST API).
Please see https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/ for more. One idea here, especially for testing, could be to use the "Basic Auth" plugin that is mentioned on that page, together with a generated application password.

Regards,
Tobias

**Comment by oldmanwerther** [comment]
@TobiasBg  -- thanks -- anyway to bipass  authentication if I'm only using it to read already published data, and using within the site itself (not an external app)?

**Comment by TobiasBg** [comment]
Hi @oldmanwerther,

from the top of my head, I can't really think of an easy or direct way here. WordPress doesn't offer a direct setting for this, and I can't find a suitable filter hook. However, I think I could add a custom filter hook in TablePress' REST API, which could then be used to achieve this. Would that work for you?

Regards,
Tobias

**Comment by oldmanwerther** [comment]
@TobiasBg  -- Yes, that would be great.

**Comment by TobiasBg** [comment]
Hi @oldmanwerther,

sure! This will be part of TablePress 2.1, coming soon :-)

Best wishes,
Tobias
