### ISSUE TITLE
Tablepress text gets white when add links

### ISSUE THREAD

**Issue by zainulabadin7** [TablePress/TablePress#190]
I am getting this issue when i add links to any field its text gets white. I have attached the screenshot.
![Tablepress](https://github.com/TablePress/TablePress/assets/159890581/4bdc4b8b-7350-40da-9aae-2be143457446)

**Comment by TobiasBg** [comment]
Hi @zainulabadin7,

most likely, the reason for this is that your theme is setting a white (or rather light gray) text color for links. To hopefully change this, please add this to the "Custom CSS" text area on the "Plugin Options" screen of TablePress:
```CSS
.tablepress a {
  text-color: #333333;
}
```
Best wishes,
Tobias

**Comment by zainulabadin7** [comment]
Hi @TobiasBg thanks for the reply. But still, it's not working when I pasted that code in the text area it removed this "text-color: #333333;" after saving it. Should I have to change my theme? But I would love to resolve it easily. Because I need your plugin to work. Thanks again
![Tablepress1](https://github.com/TablePress/TablePress/assets/159890581/1c2a09e5-2606-467b-919f-f853a37bc422)

**Comment by TobiasBg** [comment]
Hi @zainulabadin7,

ah, my bad. The correct CSS property is `color` and not `text-color`, so please try again with
```CSS
.tablepress a {
  color: #333333;
}
```
Best wishes,
Tobias

**Comment by zainulabadin7** [comment]
@TobiasBg Hi, thanks a lot. it worked I just need 1 more help when i hover its still white i want to red or any other( just need the code i will change the color) and i want to center align the whole table can you please give me css for these too?

**Comment by TobiasBg** [comment]
Hi @zainulabadin7! For that, you can use the second code example from https://tablepress.org/faq/change-color-highlighting-hovered-rows/, just add the `a` in the CSS selector as well (just like above).

For centering the table: Normally, the table takes 100% of the available content width, so that centering doesn't really make sense -- except if you want to reduce the width, then see https://tablepress.org/faq/center-table-on-the-page/, or except if the table is too wide for the content area and would actually need a solution for responsiveness, like those from https://tablepress.org/modules/responsive-tables/. Or do you want to center the text in the cells?
