### ISSUE TITLE
TablePress CSS Loads even without a Table on page

### ISSUE THREAD

**Issue by bhubbard** [TablePress/TablePress#193]
We are using Tablepress Pro with a DIVI child theme, I notice the css loads on every page, even pages without a tablepress table loading. Ideally for performance they only load on pages that have a tablepress table. 

```
<link rel='stylesheet' id='tablepress-default-css' href='https://staging-mitreengenuity.kinsta.cloud/wp-content/tablepress-combined.min.css?ver=35' type='text/css' media='all' />
<link rel='stylesheet' id='tablepress-datatables-buttons-css' href='https://staging-mitreengenuity.kinsta.cloud/wp-content/plugins/tablepress-premium/modules/css/build/datatables.buttons.css?ver=2.2.5' type='text/css' media='all' />
<link rel='stylesheet' id='tablepress-datatables-columnfilterwidgets-css' href='https://staging-mitreengenuity.kinsta.cloud/wp-content/plugins/tablepress-premium/modules/css/build/datatables.columnfilterwidgets.css?ver=2.2.5' type='text/css' media='all' />
<link rel='stylesheet' id='tablepress-responsive-tables-css' href='https://staging-mitreengenuity.kinsta.cloud/wp-content/plugins/tablepress-premium/modules/css/build/responsive-tables.css?ver=2.2.5' type='text/css' media='all' />
```

**Comment by TobiasBg** [comment]
Hi @bhubbard,

You are totally right, TablePress loads its CSS code on every page. The reason is rather simple: CSS code needs to be loaded in the page HTML's `<head>` section -- but when that is processed, it is not yet known whether there will be a table on the page! As tables can be added in various ways (Shortcodes, Block editor block, Template tags in PHP, blocks in page builders, ...) there is no reliable and backward-compatible way to detect them :-( That's why the CSS files are loaded on all pages. The good news is that they will of course be cached, so this really only is an overhead if a visitor never visits any page on the site with a table.

Now, you can however manually influence this, by using plugin filter hooks.
For example, this code snippet, e.g. in the theme's "functions.php" will result in the CSS files only being loaded on the pages with the slugs "page-1" and "page-2".

```php

// Load TablePress CSS files conditionally.

add_filter( 'tablepress_use_default_css', 'tablepress_load_default_css_conditionally' );
function tablepress_load_default_css_conditionally( $load ) {
  if ( ! is_page( array( 'page-1', 'page-2' ) ) ) {
    $load = false;
  }
  return $load;
}

add_filter( 'tablepress_custom_css_url', 'tablepress_load_custom_css_conditionally', 10, 3 );
function tablepress_load_custom_css_conditionally( $url, $file, $type ) {
  if ( ! is_page( array( 'page-1', 'page-2' ) ) ) {
    $url = '';
  }
  return $url;
}

add_filter( 'tablepress_module_enqueue_css_files', 'tablepress_load_module_css_conditionally', 10, 2 );
function tablepress_load_module_css_conditionally( $load, $module ) {
  if ( ! is_page( array( 'page-1', 'page-2' ) ) ) {
    $load = false;
  }
  return $load;
}
```

I hope this helps! :-)

**Comment by bhubbard** [comment]
@TobiasBg Thanks for the example, I will use the filters you mentioned to just load the css if a block or shortcode is used.
