### ISSUE TITLE
Import of CSV: separation character determination fails

### ISSUE THREAD

**Issue by raydiy** [TablePress/TablePress#198]
Hey @TobiasBg 

the importer behaves strange on a rather simple CSV import.
It seems the automatic determination of the separation character goes wrong.
I have attached two files: one is working, one is not.

The separation character is the semicolon – there are 20 semicolons per row in the file.
But there are rows that contain two commas and the importer determines the comma as the separation character.

In the working CSV I just removed the commas.

Only thing I can think of is, that the encoding of the files does play a role with this issue. There are also some broken german special chars like Ä,Ö etc. that did not import correct.
But I'm not sure if the encoding should play a role in this case?

[working.csv](https://github.com/user-attachments/files/15911338/working.csv)
[notworking.csv](https://github.com/user-attachments/files/15911339/notworking.csv)

**Comment by TobiasBg** [comment]
Hi @raydiy,

from what I can see, the first line in both files only has 19 semicolons, whereas the remaining three each have 20.
This seems to be throwing off the detection, so that it falls back to the comma.
When I add another semicolon in the first line of the notworking.csv, it's properly imported for me.

Best wishes,
Tobias
