### ISSUE TITLE
Error Report: HTTP 403 Error When Using Specific Words in Table Cells

### ISSUE THREAD

**Issue by janbocloud** [TablePress/TablePress#212]
I am encountering an issue with your HTML table creation tool. When entering certain phrases containing the word "Open" into a table cell, the server responds with a 403 error. Below are the details:

## Error Trigger:
The issue occurs when the following phrases or variations of them are input into a table cell:

- "Open Text Chat"
- ".Open ..."
- " Open"
- "open ..."

## Error Message:
```
Attention: Unfortunately, an error occurred. There was a problem with the server, HTTP response code 403 ().
Please see the TablePress FAQ page for suggestions.
```

## Workarounds:
When the input does not exactly match the word "Open" or certain variations (e.g., "_Open ..." or "Opened ..."), the error does not occur.

It appears that specific conditions involving the word "Open" are triggering the server's restriction or filter. Could you investigate and confirm?
If this issue is only occurring in my environment, please feel free to close this ticket.
Thank you for your attention. Please let me know if additional details or steps to reproduce are needed.

Best regards,

**Comment by TobiasBg** [comment]
Hi @janbocloud,

Thanks for opening this issue with such a detailed description, and sorry to hear that you are having trouble.

From everything that I can see, this is indeed isolated to your environment: A security software/firewall on the server is blocking the request. For more on this, please see https://tablepress.org/faq/common-errors/.
I suggest to get in touch with your hosting company's support team to relax the configuration of this software, so that the request is allowed.

Best wishes,
Tobias
